### ISSUE TITLE
uiomove の宛先を独立したリングバッファにする

### ISSUE THREAD

**Issue by moveccr** [moveccr/netbsd-src#1]
uiomove はm68kでは、ページサイズ以下の時 moves 命令、ページサイズ以上のときは MMU を設定してから memcpy なので、カーネル内でコピーが 1 段増えるとしてもページサイズ以上のバッファへ一度コピーしたほうが効率が良いのではないか？
また、mmap をサポートするときにも、バッファがもう一段あったほうが都合がいい。
このリングバッファが byte-frame 両動作すればサブフレームの問題も解決する。

**Comment by isaki68k** [comment]
5bb84bf7 (2017-12-16) までに実装できてるはず。mmap については未検討。
