### ISSUE TITLE
2^n 除算をシフトに変更する

### ISSUE THREAD

**Issue by moveccr** [moveccr/netbsd-src#3]
C99 で負数の除算は 0 への丸めと定義されているようだ。負数の右シフトは処理系定義とされているようだ。
0 への丸めを行うために m68k では 4~5 命令必要になるが、問題にならないところでは右シフトで書くほうが良かろう。

**Comment by isaki68k** [comment]
チャンネル変換は対応した。

**Comment by isaki68k** [comment]
f7c2c162 (2018-02-16) までにチャンネルボリューム、マスターボリュームも対応したので、
たぶんこれで全部じゃないかなあ。
