### ISSUE TITLE
Full/Half Duplex 問題

### ISSUE THREAD

**Issue by moveccr** [moveccr/netbsd-src#8]
そもそも検討が足りてない。Half デバイスの場合の play/rec 排他性を見せずにおくのか、もう見せて排他性をもたせるのかとか。

**Comment by isaki68k** [comment]
N8 は Half デバイスに対して、write しながら別ディスクリプタから read すると
read がブロックするようだ。詳細はしらんけど、たぶん何も考えてない。
manpage によると無音が録音されるとあるが、そうなっていないし、その仕様もどうかと思う。

一応逆側のミキサーがとまっていたら(pbusy/rbusyがfalse)で、動的に Half duplex 動作は
できなくはないと思うが(どういう問題があるかは検討していない)、
出来たとしてもタイミングが分かりづらいのと、誰も嬉しくない気がする。
オープン時にエラーで弾くなど制限したほうがいいんじゃなかろうか。

**Comment by isaki68k** [comment]
d026789b (2018-01-30) あたり。
オープン時に open mode と HW Full/Half から、ディスクリプタの Full/Half が確定し、
その後は変更できない仕様でとりあえず確定させる。
